services:
  notebook:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-normal
    image: cw-ext-notebooks:normal
    container_name: chipwhisperer-notebook
    environment:
      - JUPYTER_PORT=${JUPYTER_PORT:-8888}
      - JUPYTER_TOKEN=${JUPYTER_TOKEN:-chipwhisperer}
      - DOCKER_UID=${DOCKER_UID:-0}
      - DOCKER_GID=${DOCKER_GID:-0}
    devices:
      # - /dev/ttyUSB0:/dev/ttyUSB0
      # - /dev/ttyUSB1:/dev/ttyUSB1
      - /dev/bus/usb:/dev/bus/usb
    ports:
      - ${JUPYTER_PORT:-8888}:${JUPYTER_PORT:-8888}
    volumes:
      - ${NOTEBOOK_DIR:-./notebooks}:/workspace/notebooks
      - ${DATA_DIR:-./data}:/workspace/data
    user: "${DOCKER_UID}:${DOCKER_GID}"

