FROM ubuntu:22.04

LABEL maintener="Takuya Kojima <tkojima@hal.ipc.i.u-tokyo.ac.jp>"

ENV JUPYTER_PORT=8888
ENV NOTEBOOK_TOKEN=chipwhisperer

RUN apt update && apt install -y wget gnupg2 ca-certificates 
RUN mkdir --parents --mode=0755 /etc/apt/keyrings && \
	wget -O- https://repo.radeon.com/rocm/rocm.gpg.key  | \
    gpg --dearmor | tee /etc/apt/keyrings/rocm.gpg && \
	echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/rocm.gpg] https://repo.radeon.com/rocm/apt/6.0.1/ jammy main" | tee /etc/apt/sources.list.d/rocm.list

RUN apt update && apt install -y \
	build-essential \
	cmake \
	git \
	python3-dev \
	python3-pip \
	rocm-opencl-runtime \
	opencl-headers \
	&& rm -rf /var/lib/apt/lists/*

# pull chipwhisperer and install
RUN cd /opt && git clone https://github.com/newaetech/chipwhisperer.git && \
	cd chipwhisperer && git checkout 5.7.0 && \
	git submodule update --init jupyter && \
	pip3 install . && \
	pip3 install -r jupyter/requirements.txt

RUN pip3 install pybind11

# build & install chipwhisperer-enhanced-plugins
COPY . /opt/chipwhisperer-enhanced-plugins
RUN cd /opt/chipwhisperer-enhanced-plugins && \
	OpenCL_LIBRARY=/opt/rocm/lib/libOpenCL.so pip3 install .

RUN mkdir -p /workspace/notebooks && mkdir /workspace/data
WORKDIR /workspace

# add entrypoint
ADD ./docker/launch_notebook.sh /usr/local/bin/launch_notebook.sh
RUN chmod +x /usr/local/bin/launch_notebook.sh
ENTRYPOINT [ "/usr/local/bin/launch_notebook.sh" ]
