FROM ubuntu:24.04

LABEL maintener="Takuya Kojima <tkojima@hal.ipc.i.u-tokyo.ac.jp>"

ENV JUPYTER_PORT=8888
ENV NOTEBOOK_TOKEN=chipwhisperer

RUN apt update && apt install -y wget gnupg2 ca-certificates 
RUN mkdir --parents --mode=0755 /etc/apt/keyrings && \
	wget -O- https://repo.radeon.com/rocm/rocm.gpg.key  | \
    gpg --dearmor | tee /etc/apt/keyrings/rocm.gpg && \
	echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/rocm.gpg] https://repo.radeon.com/rocm/apt/6.3.4/ noble main" | tee /etc/apt/sources.list.d/rocm.list

RUN apt update && apt install -y \
	build-essential \
	cmake \
	git \
	python3-dev \
	python3-pip \
	python3-venv \
	rocm-opencl-runtime \
	opencl-headers \
	&& rm -rf /var/lib/apt/lists/*

# create venv
RUN python3 -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

# pull chipwhisperer and install
RUN cd /opt && git clone https://github.com/newaetech/chipwhisperer.git && \
	cd chipwhisperer && git checkout 5.7.0 && \
	git submodule update --init jupyter && \
	pip3 install . && \
	pip3 install -r jupyter/requirements.txt

RUN pip3 install pybind11

# build & install chipwhisperer-enhanced-plugins
COPY . /opt/chipwhisperer-enhanced-plugins
RUN cd /opt/chipwhisperer-enhanced-plugins && \
	OpenCL_LIBRARY=/opt/rocm/lib/libamdocl64.so pip3 install .

RUN mkdir -p /workspace/notebooks && mkdir /workspace/data
WORKDIR /workspace

# trick for non-root user setup script
RUN mkdir /var/tmp/init && chmod o+w /var/tmp/init
RUN { \
  echo 'if [ -f "/var/tmp/init/${UID}_bashrc" ]; then'; \
  echo '  source /var/tmp/init/${UID}_bashrc'; \
  echo 'fi'; \
} >> /etc/bash.bashrc

# add entrypoint
ADD ./docker/entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh
ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]

