FROM ubuntu:24.04

LABEL maintener="Takuya Kojima <tkojima@hal.ipc.i.u-tokyo.ac.jp>"

ENV JUPYTER_PORT=8888
ENV NOTEBOOK_TOKEN=chipwhisperer

RUN apt-get update && apt-get install -y \
	build-essential \
	cmake \
	git \
	python3-dev \
	python3-pip \
	python3-venv \
	&& rm -rf /var/lib/apt/lists/*

# create venv
RUN python3 -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

# pull chipwhisperer and install
RUN cd /opt && git clone https://github.com/newaetech/chipwhisperer.git && \
	cd chipwhisperer && git checkout 5.7.0 && \
	git submodule update --init jupyter && \
	/opt/venv/bin/pip3 install . && \
	/opt/venv/bin/pip3 install -r jupyter/requirements.txt

RUN /opt/venv/bin/pip3 install pybind11

# build & install chipwhisperer-enhanced-plugins
COPY . /opt/chipwhisperer-enhanced-plugins
RUN cd /opt/chipwhisperer-enhanced-plugins && /opt/venv/bin/pip3 install .

RUN mkdir -p /workspace/notebooks && mkdir /workspace/data
WORKDIR /workspace

# trick for non-root user setup script
RUN mkdir /var/tmp/init && chmod o+w /var/tmp/init
RUN { \
  echo 'if [ -f "/var/tmp/init/${UID}_bashrc" ]; then'; \
  echo '  source /var/tmp/init/${UID}_bashrc'; \
  echo 'fi'; \
} >> /etc/bash.bashrc

# add entrypoint
ADD ./docker/entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh
ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]

