name: Build Verification
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_3_10:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10.17"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip3 install pybind11
          apt install cmake

      - name: Build
        run:
          pip3 install . -v

  build_3_11:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: "3.11.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip3 install pybind11
          apt install cmake

      - name: Build
        run:
          pip3 install . -v

  build_3_12:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.12
        uses: actions/setup-python@v2
        with:
          python-version: "3.12.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip3 install pybind11
          apt install cmake

      - name: Build
        run:
          pip3 install . -v
