name: Push Docker Image
on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  push_docker_image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push normal image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile-normal
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/cw-ext-notebooks:normal-${{ github.event.release.tag_name }}

      - name: Build and CUDA image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile-nvidia
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/cw-ext-notebooks:nvidia-${{ github.event.release.tag_name }}