name: Reusable Build Workflow on Linux
on:
  workflow_call:
    inputs:
      python_version:
        required: true
        type: string
        description: 'JSON string of Python versions to use for testing'

jobs:
  buildTest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ${{ fromJson(inputs.python_versions) }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ inputs.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip3 install pybind11
          sudo apt-get update
          sudo apt-get install cmake

      - name: Build
        run:
          pip3 install . -v

