name: Reusable Build Workflow on macOS
on:
  workflow_call:
    inputs:
      python_version:
        required: true
        type: string
        description: 'JSON string of Python versions to use for testing'

jobs:
  buildTest:
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: ${{ fromJson(inputs.python_versions) }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ inputs.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}

      - name: Run install script
        run: |
          python -m pip install --upgrade pip
          bash ./install_mac.sh

